### ISSUE TITLE
Downloads get reset after closing and restarting the app

### ISSUE THREAD

**Issue by usmanthesuper** [b5i/Atwy#2] opened 2024-12-04 16:29 UTC

**Comment by b5i** [comment] 2024-12-04 18:26
Hello, could you write a quick method to reproduce the bug please?

**Comment by usmanthesuper** [comment] 2024-12-04 18:30
yes download any video then close app turn wifi off then open app the downloads will be reset

**Comment by usmanthesuper** [comment] 2024-12-04 18:33
heres the video: https://drive.google.com/file/d/1mBb3Ux70p9g84kvT-C4ITEGjTYs8nvl1/view?usp=sharing

**Comment by b5i** [comment] 2024-12-04 18:49
Thank you for that video, unfortunately, I can't reproduce the bug on my side. 
I'll add a new console feature really soon so that kind of problems can be handled better and hopefully I'll be able to fix it.

**Comment by b5i** [comment] 2024-12-05 17:51
I added the console [here](https://github.com/b5i/Atwy/commit/ffbbc9db0ea50ecd0b774a0e8ec60de89780ff4d). Could you update your version and see if there's any log concerning CoreData before quitting the app and when launching it for the second time (where the video disappears).

**Comment by usmanthesuper** [comment] 2024-12-05 17:54
Ok

**Comment by usmanthesuper** [comment] 2024-12-05 18:12
I cant find any logs about coreData also I checked on multiple devices its the same issue. is it because I changes bundle identifier and team?

**Comment by b5i** [comment] 2024-12-05 18:15
> I cant find any logs about coreData

This is odd, could you create like a pastebin containing all the logs of the app before you quit and after you re-launched it please?

> also I checked on multiple devices its the same issue. is it because I changes bundle identifier and team?

It shouldn't cause any issue as those values are not hardcoded and are retrieved at runtime, as soon as you have some logs then you should be all of Atwy's.

**Comment by b5i** [comment] 2024-12-05 18:16
Also, do you have any more logs directly in Xcode that could explain what the issue is?

**Comment by usmanthesuper** [comment] 2024-12-05 18:16
<img width="455" alt="Screenshot 2024-12-05 at 11 16 25 PM" src="https://github.com/user-attachments/assets/846b8ff2-33bc-40ea-b6ce-2266977d34ad">

are these logs helpful?

**Comment by b5i** [comment] 2024-12-05 18:17
I don't think so.

**Comment by usmanthesuper** [comment] 2024-12-05 18:17
<img width="463" alt="Screenshot 2024-12-05 at 11 17 41 PM" src="https://github.com/user-attachments/assets/74d3648b-a95a-4879-8cf1-622de532d19e">

this?

**Comment by b5i** [comment] 2024-12-05 18:19
No, those come from Atwy cleaning the logs directory (which is not empty when exporting YouTubeKit's logs).

**Comment by b5i** [comment] 2024-12-05 18:22
I think there's two options, the videos are removed from CoreData because their file doesn't exist anymore (which would happen when you re-launch the app) or there's an error when saving the entry to the database (which would happen when you still have the app running).

**Comment by usmanthesuper** [comment] 2024-12-05 18:23
I get this when video gets downloaded:
Store with identifier CA301572-B291-4F14-8F72-61CBBCD4B620 has completed
indexing and has processed history token up through <NSPersistentHistoryToken - {
    "CA301572-B291-4F14-8F72-61CBBCD4B620" = 39;
}>

**Comment by b5i** [comment] 2024-12-05 18:24
Ok then this part should be all good.

**Comment by b5i** [comment] 2024-12-05 18:25
Can you pull the repo and see if any of the new logs appear?

**Comment by usmanthesuper** [comment] 2024-12-05 18:26
I pulled but new logs did not appeared also console page in settings keeps on loading

**Comment by b5i** [comment] 2024-12-05 18:28
I fixed the console thing, can you see now?

**Comment by usmanthesuper** [comment] 2024-12-05 18:35
nope I dont see any logs

**Comment by b5i** [comment] 2024-12-05 18:50
Ok, I'm going to think about it and give you some kind of to-check list so that we can hopefully find the issue.

**Comment by usmanthesuper** [comment] 2024-12-05 18:52
ok thanks

**Comment by b5i** [comment] 2024-12-06 21:12
## To see whether the issue concerns the end of downloading operation

1. Set a breakpoint to line 440 of file `HLSDownloader.swift` just after the log
2. Start a download (download a video that you've never tried to download before), the breakpoint is reached
3. In the debug console enter `po FileManager.default.fileExists(atPath: finalURL.path())`, the result should be true
4. (Supposing you have only one download) In the debug console enter `po "https://www.youtube.com/watch?v=\(PersistenceModel.shared.getPersistenceData().downloadedVideoIds.first!.videoId)"`, check if the resulting url is the one of video that you downloaded.

Can you try this and tell me if all the steps are ok and if I have to write a procedure to test the launch of the app please?

**Comment by b5i** [comment] 2024-12-14 14:44
Should be fixed from [`4db2773`](https://github.com/b5i/Atwy/commit/4db277387c5204e3f1bb453cb40da2c56de18025), let me know if you encounter any more issues.

**Closed as completed by b5i** 2024-12-14 14:44 UTC
Labels: bug
